(add-to-list 'load-path "~/.emacs.d/lisp")

(load "straight.el")
(load "ui.el")
(load "common.el")
(load "treesitter.el")
(load "formatter.el")
(load "utils.el")
(load "evil-conf.el")
(load "markdown.el")
(load "org-config.el")
(load "lsp.el")
(load "lang.el")
(load "dap.el")
(load "vterm.el")
(load "vue.el")
